// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD78IZke5LTYheUzerxBJqlI4OFDVAK9rw',
    appId: '1:578865427893:web:8ea89694cf8bd73b4fd5fc',
    messagingSenderId: '578865427893',
    projectId: 'works-c09b2',
    authDomain: 'works-c09b2.firebaseapp.com',
    storageBucket: 'works-c09b2.appspot.com',
    measurementId: 'G-SYJVVZKW88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBede5myoSF30PgWoK0gfkICIa_ng9_4vU',
    appId: '1:578865427893:android:9c6dba2e12aacfe14fd5fc',
    messagingSenderId: '578865427893',
    projectId: 'works-c09b2',
    storageBucket: 'works-c09b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqoBF9OG03C6m8YfA_Kh3xDKja8DwP6t8',
    appId: '1:578865427893:ios:b9a87727bd7eb9ad4fd5fc',
    messagingSenderId: '578865427893',
    projectId: 'works-c09b2',
    storageBucket: 'works-c09b2.appspot.com',
    iosClientId: '578865427893-9lmjbdscuetfr2bub9epj48ul8ot17l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.works',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqoBF9OG03C6m8YfA_Kh3xDKja8DwP6t8',
    appId: '1:578865427893:ios:b9a87727bd7eb9ad4fd5fc',
    messagingSenderId: '578865427893',
    projectId: 'works-c09b2',
    storageBucket: 'works-c09b2.appspot.com',
    iosClientId: '578865427893-9lmjbdscuetfr2bub9epj48ul8ot17l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.works',
  );
}
